version: "3.9"
services:
  filemanager:
    image: filebrowser/filebrowser:latest
    ports:
      - "8080:80"
    volumes:
      - ./files:/srv
    restart: unless-stopped

  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: "@every 1m"         # 定期掃描間隔
      ND_LOGLEVEL: info                    # 日誌等級
      ND_SESSIONTIMEOUT: 240h              # 登錄會話超時
      ND_ENABLETRANSCODINGCONFIG: true     # 啟用轉碼設置
      ND_ENABLEGRAVATAR: true              # 啟用 Gravatar
      ND_ENABLESHARING: true               # 啟用共享
    volumes:
      - "./data:/data"                     # Navidrome 的數據
      - "./files:/music:ro"                # 音樂資料夾，唯讀模式

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
